name: AkatsukiRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/stxrmx666/newdf/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/stxrmx666/newdf/main/loop.bat -OutFile loop.bat
    - name: Загрузка программ.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/stxrmx666/newdf/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/stxrmx666/newdf/main/launcher/FastConfigVPS_v2.3.exe -OutFile "FastConfigVPS_v2.3.exe"
        Invoke-WebRequest https://raw.githubusercontent.com/stxrmx666/newdf/main/launcher/VisualStudio2019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Загрузка Ngrok файла.
      run: Expand-Archive ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok config add-authtoken 2uXW55i5qteXkJu2QMtMF3vm429_5cV5jmzNj9FUY3cAZeSFN
      
      
    - name: Включение доступа RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "FastConfigVPS_v2.3.exe" "C:\Users\Public\Desktop\FastConfigVPS_v2.3.exe"
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Создание туннелей.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok tcp 3389"'
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: cmd /c start.bat
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
